version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "signinwithapplebutton/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "signinwithapplebutton/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew clean assemble
      - run:
          name: Check
          command: ./gradlew lintRelease
      - store_artifacts:
          path: signinwithapplebutton/build/outputs/
          destination: core
      - store_artifacts:
          path: sample/build/outputs/
          destination: core
#      - store_test_results:
#          path: app/build/test-results
      - deploy:
          command: |
            case "$CIRCLE_BRANCH" in
            master)
              RELEASE_MODE='release'
              ;;
            develop)
              RELEASE_MODE='snapshot'
              ;;
            *)
              RELEASE_MODE=''
              echo "No release mode for branch '$CIRCLE_BRANCH'"
              ;;
            esac

            if [ "$RELEASE_MODE" ]; then
              echo "Using release mode '$RELEASE_MODE'"
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
              gpg --import --batch $HOME/secring.gpg
              ./gradlew publish -Psonatype.username="$SONATYPE_USERNAME" -Psonatype.password="$SONATYPE_PASSWORD" -Psigning.keyId=0E7A8B89 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false -PreleaseMode="$RELEASE_MODE"
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: opensource-maven
